// This file will be regenerated by: npx supabase gen types typescript --project-id <id> > src/types/database.ts
// Placeholder until connected to live Supabase project

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'kader' | 'bidan' | 'tpg' | 'kepala_puskesmas' | 'dinas' | 'admin'
export type OcrStatus = 'uploaded' | 'preprocessing' | 'detecting_table' | 'extracting_cells' | 'recognizing_text' | 'awaiting_review' | 'reviewed' | 'committed' | 'failed'
export type StatusNaik = 'N' | 'T' | 'O'
export type JenisKelamin = 'L' | 'P'

export interface Database {
  public: {
    Tables: {
      provinces: {
        Row: { id: string; kode_bps: string; nama: string; created_at: string }
        Insert: { id?: string; kode_bps: string; nama: string; created_at?: string }
        Update: { id?: string; kode_bps?: string; nama?: string; created_at?: string }
      }
      districts: {
        Row: { id: string; province_id: string | null; kode_bps: string; nama: string; created_at: string }
        Insert: { id?: string; province_id?: string | null; kode_bps: string; nama: string; created_at?: string }
        Update: { id?: string; province_id?: string | null; kode_bps?: string; nama?: string; created_at?: string }
      }
      subdistricts: {
        Row: { id: string; district_id: string | null; kode_bps: string; nama: string; created_at: string }
        Insert: { id?: string; district_id?: string | null; kode_bps: string; nama: string; created_at?: string }
        Update: { id?: string; district_id?: string | null; kode_bps?: string; nama?: string; created_at?: string }
      }
      villages: {
        Row: { id: string; subdistrict_id: string | null; kode_bps: string; nama: string; created_at: string }
        Insert: { id?: string; subdistrict_id?: string | null; kode_bps: string; nama: string; created_at?: string }
        Update: { id?: string; subdistrict_id?: string | null; kode_bps?: string; nama?: string; created_at?: string }
      }
      puskesmas: {
        Row: { id: string; district_id: string | null; kode: string; nama: string; alamat: string | null; created_at: string }
        Insert: { id?: string; district_id?: string | null; kode: string; nama: string; alamat?: string | null; created_at?: string }
        Update: { id?: string; district_id?: string | null; kode?: string; nama?: string; alamat?: string | null; created_at?: string }
      }
      posyandu: {
        Row: { id: string; puskesmas_id: string | null; village_id: string | null; kode: string; nama: string; alamat: string | null; rt: string | null; rw: string | null; created_at: string }
        Insert: { id?: string; puskesmas_id?: string | null; village_id?: string | null; kode: string; nama: string; alamat?: string | null; rt?: string | null; rw?: string | null; created_at?: string }
        Update: { id?: string; puskesmas_id?: string | null; village_id?: string | null; kode?: string; nama?: string; alamat?: string | null; rt?: string | null; rw?: string | null; created_at?: string }
      }
      user_profiles: {
        Row: { id: string; role: UserRole; nama: string; nip: string | null; phone: string | null; posyandu_id: string | null; puskesmas_id: string | null; district_id: string | null; is_active: boolean; created_at: string; updated_at: string }
        Insert: { id: string; role: UserRole; nama: string; nip?: string | null; phone?: string | null; posyandu_id?: string | null; puskesmas_id?: string | null; district_id?: string | null; is_active?: boolean; created_at?: string; updated_at?: string }
        Update: { id?: string; role?: UserRole; nama?: string; nip?: string | null; phone?: string | null; posyandu_id?: string | null; puskesmas_id?: string | null; district_id?: string | null; is_active?: boolean; created_at?: string; updated_at?: string }
      }
      children: {
        Row: { id: string; nik: string | null; no_kk: string | null; nama: string; nama_normalized: string; tanggal_lahir: string; jenis_kelamin: JenisKelamin; anak_ke: number | null; berat_lahir_kg: number | null; panjang_lahir_cm: number | null; nama_ibu: string | null; nama_ibu_normalized: string | null; nik_ibu: string | null; nama_ayah: string | null; nik_ayah: string | null; alamat: string | null; rt: string | null; rw: string | null; posyandu_id: string | null; is_active: boolean; consent_given: boolean; consent_date: string | null; consent_guardian_name: string | null; consent_guardian_relationship: string | null; created_at: string; updated_at: string; created_by: string | null }
        Insert: { id?: string; nik?: string | null; no_kk?: string | null; nama: string; nama_normalized: string; tanggal_lahir: string; jenis_kelamin: JenisKelamin; anak_ke?: number | null; berat_lahir_kg?: number | null; panjang_lahir_cm?: number | null; nama_ibu?: string | null; nama_ibu_normalized?: string | null; nik_ibu?: string | null; nama_ayah?: string | null; nik_ayah?: string | null; alamat?: string | null; rt?: string | null; rw?: string | null; posyandu_id?: string | null; is_active?: boolean; consent_given?: boolean; consent_date?: string | null; consent_guardian_name?: string | null; consent_guardian_relationship?: string | null; created_at?: string; updated_at?: string; created_by?: string | null }
        Update: Partial<Database['public']['Tables']['children']['Insert']>
      }
      measurements: {
        Row: { id: string; child_id: string; tanggal_pengukuran: string; umur_bulan: number; berat_badan_kg: number | null; tinggi_badan_cm: number | null; lingkar_kepala_cm: number | null; lila_cm: number | null; tipe_pengukuran_tb: 'PB' | 'TB' | null; zscore_bb_u: number | null; zscore_tb_u: number | null; zscore_bb_tb: number | null; status_bb_u: string | null; status_tb_u: string | null; status_bb_tb: string | null; bb_bulan_lalu_kg: number | null; kenaikan_bb_gram: number | null; kbm_gram: number | null; status_naik: StatusNaik | null; is_bgm: boolean; is_2t: boolean; has_edema: boolean; vitamin_a: boolean; pmt: boolean; asi_eksklusif: boolean | null; keterangan: string | null; source_type: string; ocr_document_id: string | null; created_at: string; updated_at: string; created_by: string | null }
        Insert: { id?: string; child_id: string; tanggal_pengukuran: string; umur_bulan: number; berat_badan_kg?: number | null; tinggi_badan_cm?: number | null; lingkar_kepala_cm?: number | null; lila_cm?: number | null; tipe_pengukuran_tb?: 'PB' | 'TB' | null; zscore_bb_u?: number | null; zscore_tb_u?: number | null; zscore_bb_tb?: number | null; status_bb_u?: string | null; status_tb_u?: string | null; status_bb_tb?: string | null; bb_bulan_lalu_kg?: number | null; kenaikan_bb_gram?: number | null; kbm_gram?: number | null; status_naik?: StatusNaik | null; is_bgm?: boolean; is_2t?: boolean; has_edema?: boolean; vitamin_a?: boolean; pmt?: boolean; asi_eksklusif?: boolean | null; keterangan?: string | null; source_type?: string; ocr_document_id?: string | null; created_at?: string; updated_at?: string; created_by?: string | null }
        Update: Partial<Database['public']['Tables']['measurements']['Insert']>
      }
      ocr_documents: {
        Row: { id: string; posyandu_id: string; original_filename: string | null; storage_path: string; file_size_bytes: number | null; mime_type: string | null; status: OcrStatus; error_message: string | null; preprocessed_path: string | null; deskew_angle: number | null; table_detection_result: Json | null; cell_extraction_result: Json | null; ocr_raw_result: Json | null; ocr_structured_result: Json | null; overall_confidence: number | null; reviewed_by: string | null; reviewed_at: string | null; review_corrections: Json | null; bulan_data: string | null; form_type: string; created_at: string; updated_at: string; uploaded_by: string | null }
        Insert: { id?: string; posyandu_id: string; original_filename?: string | null; storage_path: string; file_size_bytes?: number | null; mime_type?: string | null; status?: OcrStatus; error_message?: string | null; preprocessed_path?: string | null; deskew_angle?: number | null; table_detection_result?: Json | null; cell_extraction_result?: Json | null; ocr_raw_result?: Json | null; ocr_structured_result?: Json | null; overall_confidence?: number | null; reviewed_by?: string | null; reviewed_at?: string | null; review_corrections?: Json | null; bulan_data?: string | null; form_type?: string; created_at?: string; updated_at?: string; uploaded_by?: string | null }
        Update: Partial<Database['public']['Tables']['ocr_documents']['Insert']>
      }
      ocr_extracted_rows: {
        Row: { id: string; document_id: string; row_index: number; nama_anak: string | null; nama_anak_confidence: number | null; tanggal_lahir: string | null; tanggal_lahir_confidence: number | null; umur: string | null; umur_confidence: number | null; jenis_kelamin: string | null; jenis_kelamin_confidence: number | null; nama_ibu: string | null; nama_ibu_confidence: number | null; alamat: string | null; alamat_confidence: number | null; bb_lalu: string | null; bb_lalu_confidence: number | null; bb_sekarang: string | null; bb_sekarang_confidence: number | null; tb: string | null; tb_confidence: number | null; status_nt: string | null; status_nt_confidence: number | null; bbox: Json | null; is_reviewed: boolean; is_approved: boolean; matched_child_id: string | null; corrections: Json | null; created_at: string }
        Insert: { id?: string; document_id: string; row_index: number; nama_anak?: string | null; nama_anak_confidence?: number | null; tanggal_lahir?: string | null; tanggal_lahir_confidence?: number | null; umur?: string | null; umur_confidence?: number | null; jenis_kelamin?: string | null; jenis_kelamin_confidence?: number | null; nama_ibu?: string | null; nama_ibu_confidence?: number | null; alamat?: string | null; alamat_confidence?: number | null; bb_lalu?: string | null; bb_lalu_confidence?: number | null; bb_sekarang?: string | null; bb_sekarang_confidence?: number | null; tb?: string | null; tb_confidence?: number | null; status_nt?: string | null; status_nt_confidence?: number | null; bbox?: Json | null; is_reviewed?: boolean; is_approved?: boolean; matched_child_id?: string | null; corrections?: Json | null; created_at?: string }
        Update: Partial<Database['public']['Tables']['ocr_extracted_rows']['Insert']>
      }
      audit_logs: {
        Row: { id: string; user_id: string | null; user_role: UserRole | null; action: string; resource_type: string | null; resource_id: string | null; details: Json | null; ip_address: string | null; user_agent: string | null; created_at: string }
        Insert: { id?: string; user_id?: string | null; user_role?: UserRole | null; action: string; resource_type?: string | null; resource_id?: string | null; details?: Json | null; ip_address?: string | null; user_agent?: string | null; created_at?: string }
        Update: Partial<Database['public']['Tables']['audit_logs']['Insert']>
      }
      skdn_monthly: {
        Row: { id: string; posyandu_id: string; bulan: string; s_sasaran: number; k_ber_kms: number; d_ditimbang: number; n_naik: number; bgm_count: number; t2_count: number; stunting_count: number; wasting_count: number; underweight_count: number; overweight_count: number; ratio_ds: number | null; ratio_nd: number | null; ratio_ks: number | null; calculated_at: string }
        Insert: { id?: string; posyandu_id: string; bulan: string; s_sasaran?: number; k_ber_kms?: number; d_ditimbang?: number; n_naik?: number; bgm_count?: number; t2_count?: number; stunting_count?: number; wasting_count?: number; underweight_count?: number; overweight_count?: number; ratio_ds?: number | null; ratio_nd?: number | null; ratio_ks?: number | null; calculated_at?: string }
        Update: Partial<Database['public']['Tables']['skdn_monthly']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      user_role: UserRole
      ocr_status: OcrStatus
    }
  }
}
