/**
 * WHO Weight-for-Age (WFA) LMS values — Boys, 0-60 months.
 *
 * Source: WHO Child Growth Standards (2006)
 * https://www.who.int/tools/child-growth-standards/standards/weight-for-age
 *
 * Monthly anchor points (month 0 = birth, month 60 = 5yr).
 * Use interpolateDaily() to generate daily values (0-1856 days).
 */
import type { LMSRow } from '@/types/who'

/** Monthly LMS anchor points: [month, L, M, S] */
export const WFA_BOYS_MONTHLY: readonly [number, number, number, number][] = [
  [0,  -0.3521, 3.3464, 0.14602],
  [1,  -0.3521, 4.4709, 0.13395],
  [2,  -0.3521, 5.5675, 0.12385],
  [3,  -0.3521, 6.3762, 0.11727],
  [4,  -0.3521, 7.0023, 0.11316],
  [5,  -0.3521, 7.5105, 0.10980],
  [6,  -0.3521, 7.9340, 0.10764],
  [7,  -0.3521, 8.2970, 0.10583],
  [8,  -0.3521, 8.6151, 0.10444],
  [9,  -0.3521, 8.9014, 0.10335],
  [10, -0.3521, 9.1649, 0.10254],
  [11, -0.3521, 9.4122, 0.10195],
  [12, -0.3521, 9.6479, 0.10156],
  [13, -0.3521, 9.8749, 0.10137],
  [14, -0.3521, 10.0953, 0.10130],
  [15, -0.3521, 10.3108, 0.10134],
  [16, -0.3521, 10.5228, 0.10149],
  [17, -0.3521, 10.7319, 0.10175],
  [18, -0.3521, 10.9385, 0.10207],
  [19, -0.3521, 11.1430, 0.10247],
  [20, -0.3521, 11.3462, 0.10294],
  [21, -0.3521, 11.5486, 0.10347],
  [22, -0.3521, 11.7504, 0.10404],
  [23, -0.3521, 11.9514, 0.10466],
  [24, -0.3521, 12.1515, 0.10536],
  [25, -0.3521, 12.3502, 0.10604],
  [26, -0.3521, 12.5466, 0.10678],
  [27, -0.3521, 12.7401, 0.10756],
  [28, -0.3521, 12.9303, 0.10838],
  [29, -0.3521, 13.1169, 0.10920],
  [30, -0.3521, 13.3000, 0.11005],
  [31, -0.3521, 13.4798, 0.11090],
  [32, -0.3521, 13.6564, 0.11176],
  [33, -0.3521, 13.8299, 0.11261],
  [34, -0.3521, 14.0006, 0.11347],
  [35, -0.3521, 14.1688, 0.11433],
  [36, -0.3521, 14.3345, 0.11519],
  [37, -0.3521, 14.4981, 0.11604],
  [38, -0.3521, 14.6596, 0.11688],
  [39, -0.3521, 14.8193, 0.11771],
  [40, -0.3521, 14.9774, 0.11854],
  [41, -0.3521, 15.1340, 0.11935],
  [42, -0.3521, 15.2893, 0.12016],
  [43, -0.3521, 15.4433, 0.12096],
  [44, -0.3521, 15.5964, 0.12175],
  [45, -0.3521, 15.7488, 0.12253],
  [46, -0.3521, 15.9002, 0.12329],
  [47, -0.3521, 16.0508, 0.12404],
  [48, -0.3521, 16.2009, 0.12477],
  [49, -0.3521, 16.3503, 0.12548],
  [50, -0.3521, 16.4994, 0.12617],
  [51, -0.3521, 16.6483, 0.12685],
  [52, -0.3521, 16.7970, 0.12751],
  [53, -0.3521, 16.9458, 0.12815],
  [54, -0.3521, 17.0948, 0.12878],
  [55, -0.3521, 17.2441, 0.12939],
  [56, -0.3521, 17.3940, 0.12999],
  [57, -0.3521, 17.5445, 0.13057],
  [58, -0.3521, 17.6958, 0.13113],
  [59, -0.3521, 17.8479, 0.13168],
  [60, -0.3521, 18.0010, 0.13221],
] as const

/**
 * Pre-computed daily WFA table for boys (0-1856 days).
 * Generated by linear interpolation of monthly anchors.
 * Computed lazily on first access.
 */
let _cachedDaily: readonly LMSRow[] | null = null

export function getWfaBoys(): readonly LMSRow[] {
  if (_cachedDaily) return _cachedDaily
  _cachedDaily = interpolateDaily(WFA_BOYS_MONTHLY)
  return _cachedDaily
}

/** Linear interpolation of monthly LMS to daily LMS (0-1856 days). */
function interpolateDaily(
  monthly: readonly (readonly [number, number, number, number])[]
): LMSRow[] {
  const DAYS_PER_MONTH = 30.4375 // WHO standard
  const maxDay = 1856
  const result: LMSRow[] = []

  for (let day = 0; day <= maxDay; day++) {
    const monthExact = day / DAYS_PER_MONTH
    // Find bounding monthly anchors
    let lowerIdx = Math.floor(monthExact)
    if (lowerIdx >= monthly.length - 1) lowerIdx = monthly.length - 2
    if (lowerIdx < 0) lowerIdx = 0
    const upperIdx = lowerIdx + 1

    const [, L0, M0, S0] = monthly[lowerIdx]
    const [, L1, M1, S1] = monthly[upperIdx]

    const frac = monthExact - lowerIdx

    result.push({
      day,
      L: L0 + (L1 - L0) * frac,
      M: M0 + (M1 - M0) * frac,
      S: S0 + (S1 - S0) * frac,
    })
  }

  return result
}
